# Generated by Django 3.0.8 on 2020-07-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='host',
        ),
    ]
